// <auto-generated />
using System;
using LabelPrinter.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabelPrinter.Migrations
{
    [DbContext(typeof(LabelPrinterDbContext))]
    [Migration("20260923221639_AddIsRawDataToPrintJob")]
    partial class AddIsRawDataToPrintJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LabelPrinter.Core.Entities.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .HasMaxLength(8000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditEvents_CreatedAt");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_AuditEvents_EventType");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_AuditEvents_JobId");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.DiscoveredPrinter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DriverName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrinterStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WindowsName")
                        .IsUnique()
                        .HasDatabaseName("IX_DiscoveredPrinters_WindowsName");

                    b.ToTable("DiscoveredPrinters");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrintAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrinterName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SpoolerJobId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .HasDatabaseName("IX_PrintAttempts_JobId");

                    b.ToTable("PrintAttempts");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArchivePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedEncoding")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("DocumentHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtractedPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRawData")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsReprint")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("LabelSize")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marketplace")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MarketplaceRaw")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("OrderReference")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OriginalJobId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PackageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PackageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PdfPath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrinterProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_PrintJobs_CreatedAt");

                    b.HasIndex("Marketplace")
                        .HasDatabaseName("IX_PrintJobs_Marketplace");

                    b.HasIndex("OriginalHash")
                        .HasDatabaseName("IX_PrintJobs_OriginalHash");

                    b.HasIndex("PrinterProfileId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_PrintJobs_Status");

                    b.ToTable("PrintJobs");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrinterProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultCopies")
                        .HasColumnType("INTEGER");

                    b.Property<double>("DefaultLabelHeightMm")
                        .HasColumnType("REAL");

                    b.Property<double>("DefaultLabelWidthMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Dpi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DriverName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRetries")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PortName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintTimeoutSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindowsPrinterName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Enabled")
                        .HasDatabaseName("IX_PrinterProfiles_Enabled");

                    b.HasIndex("WindowsPrinterName")
                        .HasDatabaseName("IX_PrinterProfiles_WindowsPrinterName");

                    b.ToTable("PrinterProfiles");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrinterRoutingRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LabelSize")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marketplace")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrinterProfileId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PrinterProfileId");

                    b.ToTable("PrinterRoutingRules");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.AuditEvent", b =>
                {
                    b.HasOne("LabelPrinter.Core.Entities.PrintJob", "Job")
                        .WithMany("AuditEvents")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Job");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrintAttempt", b =>
                {
                    b.HasOne("LabelPrinter.Core.Entities.PrintJob", "Job")
                        .WithMany("Attempts")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrintJob", b =>
                {
                    b.HasOne("LabelPrinter.Core.Entities.PrinterProfile", "PrinterProfile")
                        .WithMany("Jobs")
                        .HasForeignKey("PrinterProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("PrinterProfile");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrinterRoutingRule", b =>
                {
                    b.HasOne("LabelPrinter.Core.Entities.PrinterProfile", "PrinterProfile")
                        .WithMany("RoutingRules")
                        .HasForeignKey("PrinterProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrinterProfile");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrintJob", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("AuditEvents");
                });

            modelBuilder.Entity("LabelPrinter.Core.Entities.PrinterProfile", b =>
                {
                    b.Navigation("Jobs");

                    b.Navigation("RoutingRules");
                });
#pragma warning restore 612, 618
        }
    }
}
